node:                    # logger named «node»
    severity: Warning    # severity for logger «node»
    file: skovoroda.log  # messages for «node» will be sent to skovoroda.log
    comm:                # logger named «node.comm»
        severity: Info   # severity for logger «node.comm» 
        file: patak.log  # messages will be also printed to patak.log
